### ISSUE TITLE
PWOBot subdirectory missing

### ISSUE THREAD

**Issue by Neo23x0** [pan-unit42/iocs#1]
The pwobot IOC directory mentioned in this report is missing. 
Maybe committed but not pushed?

http://researchcenter.paloaltonetworks.com/2016/04/unit42-python-based-pwobot-targets-european-organizations/

**Comment by scottmi** [comment]
looks like its there, is it working for you now?

**Comment by Neo23x0** [comment]
Yes, great, thanks.
