### ISSUE TITLE
Many RFC5735 CIDR blocks in the list "The Curious Case of Notepad and Chthonic"

### ISSUE THREAD

**Issue by adulau** [pan-unit42/iocs#3]
Many RFC5735 CIDR blocks in the list "The Curious Case of Notepad and Chthonic". Could you review it? Thank you.

**Comment by karttoon** [comment]
Do you have any examples you can point to adulau? I did a quick check on the IP list and there are no RFC5735 within it. If you're referring to a domain in the Domain list then it's absolutely possible and probably quite likely to have RFC5735/1918 addresses. It's fairly common for malicious domains to resolve these addresses when not in use.

**Comment by alateeq99** [comment]
Uploading

**Comment by alateeq99** [comment]
I want you to
