### ISSUE TITLE
The Kind of Public Reports

### ISSUE THREAD

**Issue by carrie0307** [pan-unit42/iocs#5]
Execuse me, are the IOCs only from  Unit 42 'APT' Public Reports or from all kinds of Public Reports?
Thank you so much!

**Comment by karttoon** [comment]
They should be related to data PANW has - either blogs or intel sharing efforts; however, it is highly likely there will be overlap in reporting of IoC's with other public reports.

**Comment by carrie0307** [comment]
I got it, Thank you!
